server:
  port: 4017

## DataSource Properties
spring:
  data:
    mongodb:
      authentication-database: admin
      database: currentasdumdb
      ##host: 157.245.219.63
      host: 64.110.26.154
      ##password: secret
      password: 48QmU9CXJZChyHHSCwG8EuU6gr8yk755
      ##username: devssd
      username: admin
  datasource:
    username: postgres
    password: 5cutnWB55rx2NdBjTcWmckS7wbbjSQ6b
    url: jdbc:postgresql://103.214.108.154:5432/locsender
    initialization-mode: never
    driver-class-name: org.postgresql.Driver
app:
   jwtSecret: CdSEN8y2mqjzLIEuArqVuiOKk5YtNaSc
   jwtExpirationInMs: 999999999
